version: 1.0.0-alpha-{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
configuration: Release
before_build: 
  - ps: dotnet restore
build:
  project: IvorySharp.sln
  parallel: true
  verbosity: minimal
after_build:
  - ps: cd benchmarks\IvorySharp.Benchmark
  - ps: dotnet run IvorySharp.Benchmark.csproj -c Release --framework net461 --filter *
