version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
configuration: Release
before_build: 
  - ps: cd src
  - ps: dotnet restore
build:
  parallel: true
  verbosity: minimal
after_build:
  - ps: cd src/IvorySharp.Benchmark
  - ps: dotnet run IvorySharp.Benchmark.csproj -c Release
