language: csharp

matrix:
  include:
    - dotnet: 2.2
      mono: none
      before_install:
        - dotnet --version
      install:
        - dotnet restore IvorySharp.sln
      script: 
        - dotnet build IvorySharp.sln
        - cd tests/IvorySharp.Tests
        - dotnet xunit -fxversion $(ls /usr/share/dotnet/shared/Microsoft.NETCore.App/)
