language: csharp

matrix:
  include:
    - dotnet: 2.1.302
      mono: none
      before_install:
        - dotnet --version
      install:
        - dotnet restore src/IvorySharp.sln
      script: 
        - dotnet build src/IvorySharp.sln
        - cd src/IvorySharp.Tests
        - dotnet xunit -fxversion $(ls /usr/share/dotnet/shared/Microsoft.NETCore.App/)
        - cd ../IvorySharp.Benchmark
        - dotnet run IvorySharp.Benchmark.csproj -c Release --filter *BenchmarkDispatch*
