version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
skip_tags: true
configuration: Release
before_build:
  - ps: dotnet restore
build:
  parallel: true
  verbosity: minimal
before_test:
  - ps: dotnet test "IvorySharp.Tests\IvorySharp.Tests.csproj"