version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
configuration: Release
before_build: 
  - ps: >-
  ./build/install-dotnet.ps1 -Version 2.0.0
   dotnet restore
build:
  parallel: true
  verbosity: minimal
before_test:
  - ps: dotnet test "IvorySharp.Tests\IvorySharp.Tests.csproj"