version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
configuration: Release
before_build: 
  - ps: ./build/dotnet-install.ps1 -Channel 2.0
  - ps: dotnet --version
  - ps: dotnet restore
build:
  parallel: true
  verbosity: minimal